language: minimal
sudo: required
addons:
  apt:
    packages:
      - docker-ce # use experimental features

services:
  - docker

before_install:
  - docker --version  # document the version travis is using
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker && echo '{"experimental":"enabled"}' | tee $HOME/.docker/config.json
  - sudo service docker restart

install:
  - make qemu

matrix:
  include:
    - env: TAG=base       ARCH=amd64   BUNDLE=slim
    - env: TAG=base       ARCH=arm32v7 BUNDLE=slim
    - env: TAG=base       ARCH=arm32v6 BUNDLE=slim
    - env: TAG=base       ARCH=amd64   BUNDLE=build
    - env: TAG=base       ARCH=arm32v7 BUNDLE=build
    - env: TAG=base       ARCH=arm32v6 BUNDLE=build
    - env: TAG=bots       ARCH=amd64   BUNDLE=slim
    - env: TAG=bots       ARCH=arm32v7 BUNDLE=slim
    - env: TAG=bots       ARCH=arm32v6 BUNDLE=slim
    - env: TAG=bots       ARCH=amd64   BUNDLE=build
    - env: TAG=bots       ARCH=arm32v7 BUNDLE=build
    - env: TAG=bots       ARCH=arm32v6 BUNDLE=build
    - env: TAG=automation ARCH=amd64   BUNDLE=slim
    - env: TAG=automation ARCH=arm32v7 BUNDLE=slim
    - env: TAG=automation ARCH=arm32v6 BUNDLE=slim
    - env: TAG=automation ARCH=amd64   BUNDLE=build
    - env: TAG=automation ARCH=arm32v7 BUNDLE=build
    - env: TAG=automation ARCH=arm32v6 BUNDLE=build

script: 
   - travis_wait 60 make env
   - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
   - make push

after_success:
   - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
   - make manifest
